services:
  prusalink:
    container_name: prusalink
    hostname: prusalink
    image: prusalink
    privileged: true
    ports:
      - 31050:8080
    volumes:
      - "/mnt/Fast Pool/Apps/PursaLink/Config:/etc/prusalink"
      - "/mnt/Fast Pool/Apps/PursaLink/Data:/home/pi"
